# Generated by Django 5.0.2 on 2024-03-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0003_alter_orderdetails_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
