# Generated by Django 5.0.2 on 2024-03-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0004_alter_paymentdetails_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
