# Generated by Django 5.0.2 on 2024-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0005_alter_orderdetails_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
