# Generated by Django 5.0.2 on 2024-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0006_alter_useraddress_city'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name'], name='MIaC_user_first_n_f7c3cd_idx'),
        ),
    ]
