# Generated by Django 5.0.2 on 2024-04-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0008_userpayment_miac_userpa_user_id_10272b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userpayment',
            name='MIaC_userpa_user_id_10272b_idx',
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='payment_type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='provider',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
