# Generated by Django 5.0.2 on 2024-04-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0009_remove_userpayment_miac_userpa_user_id_10272b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
