# Generated by Django 5.0.2 on 2024-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0012_alter_useraddress_city_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderdetails',
            index=models.Index(fields=['user', 'order_date', 'total'], name='MIaC_orderd_user_id_affbd6_idx'),
        ),
    ]
