# Generated by Django 5.0.2 on 2024-04-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0013_orderdetails_miac_orderd_user_id_affbd6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
