# Generated by Django 5.0.2 on 2024-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0014_alter_price_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['name', 'phone'], name='MIaC_traine_name_304b4e_idx'),
        ),
    ]
