# Generated by Django 5.0.2 on 2024-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0015_trainer_miac_traine_name_304b4e_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['name', 'price'], name='MIaC_traini_name_66a3a6_idx'),
        ),
    ]
