# Generated by Django 5.0.2 on 2024-04-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0016_training_miac_traini_name_66a3a6_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['start_date', 'end_date'], name='MIaC_subscr_start_d_41f167_idx'),
        ),
    ]
