# Generated by Django 5.0.2 on 2024-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIaC', '0017_subscription_miac_subscr_start_d_41f167_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'training', 'subscription_type'], name='MIaC_orderi_order_i_497373_idx'),
        ),
    ]
